name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_activity: yes
          plugin_activity_limit: 5           # Limit to 5 events
          plugin_activity_load: 100          # Load up to 100 recent events from API (should be higher than "limit")
          plugin_activity_days: 14           # Keep only events from last 14 days (set to 0 for no limit)
          plugin_activity_filter: all        # Show all events (use table above to filter events types)
          plugin_activity_visibility: public # Only display public events
          plugin_activity_timestamps: yes    # Display events timestamps
          plugin_activity_skipped: repo      # Ignored repositories
          plugin_achievements: yes
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: detailed  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: icons    # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
